# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dewey < Formula
  desc "Knowledge graph MCP server with persistence, semantic search, and pluggable content sources"
  homepage "https://github.com/unbound-force/dewey"
  version "0.1.0"
  license "MIT"

  depends_on "ollama" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unbound-force/dewey/releases/download/v0.1.0/dewey_0.1.0_darwin_amd64.tar.gz"
      sha256 "ddc1beaad233df5bb602c2623d564be4471e1f6e0f5182aa4eb05e4a58f683b7"

      define_method(:install) do
        bin.install "dewey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unbound-force/dewey/releases/download/v0.1.0/dewey_0.1.0_darwin_arm64.tar.gz"
      sha256 "3441ffd70effdde04276a35ae2af91f85dc2f2af00368c3d3d80eb1dbd2dd0f1"

      define_method(:install) do
        bin.install "dewey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/dewey/releases/download/v0.1.0/dewey_0.1.0_linux_amd64.tar.gz"
      sha256 "f2875fdcad16a3b23bdfc230b8f5bce74c5541dc594210bca6e6531a1815555f"
      define_method(:install) do
        bin.install "dewey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/dewey/releases/download/v0.1.0/dewey_0.1.0_linux_arm64.tar.gz"
      sha256 "54e532a1db49a89e9ed0bdc76ad9b17c5bc5828ab0485cd116f9ff1fb5f123e7"
      define_method(:install) do
        bin.install "dewey"
      end
    end
  end
end
