# This file was generated by GoReleaser. DO NOT EDIT.
cask "dewey" do
  name "dewey"
  desc "Knowledge graph MCP server with persistence, semantic search, and pluggable content sources"
  homepage "https://github.com/unbound-force/dewey"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dewey"
  depends_on cask: [
      "ollama-app",
    ]

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_amd64.tar.gz"
      sha256 "44fc4a34e0a570928ef7e36e961702b91d6748f55a36aa48cc62dd8d2dce5e35"
    end
    on_arm do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_arm64.tar.gz"
      sha256 "5b5fd8af8b20fdba4de54fa67d99a4d6023262deb52f8708c264551c5d3e413f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_amd64.tar.gz"
      sha256 "b37afe943aa7db9cbced315f77e28d6b0c20476ae04c502ef1fec4d81ba04fc5"
    end
    on_arm do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_arm64.tar.gz"
      sha256 "7d17ad9dd46cc13153069bc3212cfb2f961a887caa0061029ac011e0945db406"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dewey"]
    end
  end

  # No zap stanza required
end
