# This file was generated by GoReleaser. DO NOT EDIT.
cask "dewey" do
  version "3.5.1"

  on_macos do
    on_arm do
      sha256 "83edaf5523bbba4d87e4bed18a79c89adf2c8d6854d5efc40dcae9200a7863d0"
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d16c6be698f0dd8858bde5e988dcd14f02d4a2b102a52d00e01a03ec2143f597"
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ccef2d2db438a9c7d57a81427cd32360080fe87d06a3d4fea6ba62736e913068"
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "12c6a0df1e23f408b9d9da329b40e58dc31f28a50ad58622f261d076d2fe4701"
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dewey"
  desc "Knowledge graph MCP server with persistence, semantic search, and pluggable content sources"
  homepage "https://github.com/unbound-force/dewey"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "ollama-app",
    ]

  binary "dewey"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dewey"]
    end
  end

  # No zap stanza required
end
