# This file was generated by GoReleaser. DO NOT EDIT.
cask "dewey" do
  name "dewey"
  desc "Knowledge graph MCP server with persistence, semantic search, and pluggable content sources"
  homepage "https://github.com/unbound-force/dewey"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dewey"
  depends_on cask: [
      "ollama-app",
    ]

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_amd64.tar.gz"
      sha256 "ea51c545439d92c4031e52fe781ac1f03211c8241580f41dbe42f429085f984d"
    end
    on_arm do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_darwin_arm64.tar.gz"
      sha256 "c4d6968ac01e2db710294c5e10b8caa298c2a682b72b88d6999e315ca625bfa6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_amd64.tar.gz"
      sha256 "71e18f5798f0999f0a9743541b47ea17947dc96f066fa57d4c9e685eeed6919d"
    end
    on_arm do
      url "https://github.com/unbound-force/dewey/releases/download/v#{version}/dewey_#{version}_linux_arm64.tar.gz"
      sha256 "2d7108f06cee1228eef2c7aa925bf9913ffc28c1917cf43a7619c45d5a06fee2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dewey"]
    end
  end

  # No zap stanza required
end
