# This file was generated by GoReleaser. DO NOT EDIT.
cask "gaze" do
  name "gaze"
  desc "Test quality analysis via side effect detection for Go"
  homepage "https://github.com/unbound-force/gaze"
  version "1.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gaze"

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_darwin_amd64.tar.gz"
      sha256 "5ff8752a8148060da722dade2dfeaca4b5fd210aab822b93bc9c32cf25e734fd"
    end
    on_arm do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_darwin_arm64.tar.gz"
      sha256 "d97f6772f67286bd37b168aead548b2b08b08df34775d41054be8a8ab60ba642"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_linux_amd64.tar.gz"
      sha256 "ba3fd70078973dfc276622f3f5fd686d681a8e42ada05a78d58965d56d1adfd1"
    end
    on_arm do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_linux_arm64.tar.gz"
      sha256 "151d29e4914f262b3e18f7e070dbd0c9899202d4124d5298d7b2809f828ee107"
    end
  end

  # No zap stanza required
end
