# This file was generated by GoReleaser. DO NOT EDIT.
cask "gaze" do
  name "gaze"
  desc "Test quality analysis via side effect detection for Go"
  homepage "https://github.com/unbound-force/gaze"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gaze"

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_darwin_amd64.tar.gz"
      sha256 "ced05646f90a9c5c3eb9e6672055f16aea16711058e60c7efb6d48e0c36f13b2"
    end
    on_arm do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_darwin_arm64.tar.gz"
      sha256 "a826e21d65de5a898a2a279c0875940aa7d9308c63c18ee832511ddfaf87dc78"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_linux_amd64.tar.gz"
      sha256 "0f34c8e699a892d0cf028c4c492de404cf4b4c5a68a36e22f0fc6259478e8273"
    end
    on_arm do
      url "https://github.com/unbound-force/gaze/releases/download/v#{version}/gaze_#{version}_linux_arm64.tar.gz"
      sha256 "53e7099c3f7fec27590f79856388d93a4046507d1c2ce31be7dc6aabf17e9e43"
    end
  end

  # No zap stanza required
end
