# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicator" do
  version "0.5.2-rc.1"

  on_macos do
    on_arm do
      sha256 "62f273ec23f7002d7f0769fc688612657306555e7c49f5f3140e5ee4981944f0"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "92e01ad5aa2ea46c8268dcd5b9c982ae7075909656a01d39090282f763aa156c"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b046bdca7400a2783fb318fb15d8eb5258e0b771f2d14e2754b7f176c64dccc0"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_amd64.tar.gz"
    end
  end

  name "replicator"
  desc "Multi-agent coordination for AI coding agents"
  homepage "https://github.com/unbound-force/replicator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/replicator"]
    end
  end

  # No zap stanza required
end
