# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicator" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "ef0f3e37f338c05c68d2bcb25ce40c1257ea0b366ef130b1d836155bad4e3899"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "427207b870dea8d980b2745d2d15df861befe2effb0dad40f955c09e647812f7"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd88cf04df4d812363c07f552d0db5b20c36a0a6cb83b7287de34ef807fe130c"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_amd64.tar.gz"
    end
  end

  name "replicator"
  desc "Multi-agent coordination for AI coding agents"
  homepage "https://github.com/unbound-force/replicator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/replicator"]
    end
  end

  # No zap stanza required
end
