# This file was generated by GoReleaser. DO NOT EDIT.
cask "replicator" do
  version "0.5.0-rc.1"

  on_macos do
    on_arm do
      sha256 "e0d6a65d6a678fd83e9ac0e1d33c3f48fc8e0019e4a4e719d4ed60ecb42c0a50"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b03c68bcfc3ca702f1d0d9d6bc34a3406e801df02b7dd212a360c6693f30c6fa"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2293e6d00ae61ad9fe0dfbe17f49d9f4c65ced5fe6d1c19c8e8f69c9b3fc5791"
      url "https://github.com/unbound-force/replicator/releases/download/v#{version}/replicator_#{version}_linux_arm64.tar.gz"
    end
  end

  name "replicator"
  desc "Multi-agent coordination for AI coding agents"
  homepage "https://github.com/unbound-force/replicator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "replicator"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/replicator"]
    end
  end

  # No zap stanza required

end
