# This file was generated by GoReleaser. DO NOT EDIT.
cask "unbound-force" do
  version "0.19.1"

  on_macos do
    on_arm do
      sha256 "6b06c481eff921ba92fe62e277e6d32eb636bdbdeae259edd4cfdff92034a426"
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5568afcedb4b39236cfeb6ff1f7e117e27d26867d0d66c2cdd577435fd28452"
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1395de7c87cefc493b8a378bd36b4ab2bc3c78e3454c641bd56dc06fe0de2ad8"
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "50e5d83f93fac449cb12a5ff707fc0a916a1faddf9b8b175e4385df6408290d4"
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_amd64.tar.gz"
    end
  end

  name "unbound-force"
  desc "Unbound Force specification framework toolkit"
  homepage "https://github.com/unbound-force/unbound-force"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "dewey",
    ]

  binary "unbound-force"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/unbound-force"]
      symlink "unbound-force", "{{HOMEBREW_PREFIX}}/bin/uf", overwrite: true
    end
  end

  # No zap stanza required
end
