# This file was generated by GoReleaser. DO NOT EDIT.
cask "unbound-force" do
  name "unbound-force"
  desc "Unbound Force specification framework toolkit"
  homepage "https://github.com/unbound-force/unbound-force"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unbound-force"
  depends_on cask: [
      "dewey",
    ]

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_amd64.tar.gz"
      sha256 "824d7638d44813bf5a32a183b9da6343ccdfeeb2590d3e9fa96c38580b9afff7"
    end
    on_arm do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_arm64.tar.gz"
      sha256 "6cf9f0999bd8519e2e5798652730b823fc8b9528112411f90ad0180c7f113077"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_amd64.tar.gz"
      sha256 "1ef9fdbcf81295e689bcb0d244a5be86cc0b998f7103161e3d380b2866b26062"
    end
    on_arm do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_arm64.tar.gz"
      sha256 "f0043b8ed0cb841e764b144e40f59a1e2699b2cf61137fea87cd1763a960f100"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unbound-force"]
      # Create uf symlink alias for daily-use convenience (FR-002/FR-009).
      system_command "/bin/ln", args: ["-sf", "#{staged_path}/unbound-force", "#{HOMEBREW_PREFIX}/bin/uf"]
    end
  end

  # No zap stanza required
end
