# This file was generated by GoReleaser. DO NOT EDIT.
cask "unbound-force" do
  name "unbound-force"
  desc "Unbound Force specification framework toolkit"
  homepage "https://github.com/unbound-force/unbound-force"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unbound-force"
  depends_on cask: [
      "dewey",
    ]

  on_macos do
    on_intel do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_amd64.tar.gz"
      sha256 "4501d1d8a066558853ab4b582678c0eb88b348b2a1b1b69d048065278151383b"
    end
    on_arm do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_darwin_arm64.tar.gz"
      sha256 "12540de226902dc95ccb9d184f86ff7b8240f11a86fb07f466227d38a508319a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_amd64.tar.gz"
      sha256 "9e81a1cabfd621156582535b2096230fb45cc50ac609adc383c3fd11fa900622"
    end
    on_arm do
      url "https://github.com/unbound-force/unbound-force/releases/download/v#{version}/unbound-force_#{version}_linux_arm64.tar.gz"
      sha256 "5048f430293484baaad4e4424abd4220d88f04720f0448ad7c51fc3e2d59b013"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unbound-force"]
      # Create uf symlink alias for daily-use convenience (FR-002/FR-009).
      system_command "/bin/ln", args: ["-sf", "#{staged_path}/unbound-force", "#{HOMEBREW_PREFIX}/bin/uf"]
    end
  end

  # No zap stanza required
end
