# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnboundForce < Formula
  desc "Unbound Force specification framework toolkit"
  homepage "https://github.com/unbound-force/unbound-force"
  version "0.16.0-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.2/unbound-force_0.16.0-rc.2_darwin_amd64.tar.gz"
      sha256 "b93d4d9c827f1b5c5ccdde4dd15ca4873449f3cdf8f1ac8bd3f69c0f9c9a8494"

      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.2/unbound-force_0.16.0-rc.2_darwin_arm64.tar.gz"
      sha256 "78b80374efe2b30492bf6ddabe9bdee110ad7077b7e47ff601163bbef87ffe90"

      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.2/unbound-force_0.16.0-rc.2_linux_amd64.tar.gz"
      sha256 "671acf1eded07e858a9081715d78d9b21da05c1049fd7285606168dfc3168bfb"
      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.2/unbound-force_0.16.0-rc.2_linux_arm64.tar.gz"
      sha256 "797ce7fda99946cd51d11feab1565c5e2c6b80135d87eae36d958eafd71bacc7"
      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
  end
end
