# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnboundForce < Formula
  desc "Unbound Force specification framework toolkit"
  homepage "https://github.com/unbound-force/unbound-force"
  version "0.16.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.1/unbound-force_0.16.0-rc.1_darwin_amd64.tar.gz"
      sha256 "64d488692941e21cb514aee7a35f36ae9a75cf30bad48c213cfbd65d9efec148"

      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.1/unbound-force_0.16.0-rc.1_darwin_arm64.tar.gz"
      sha256 "86c5a3fc5b86513aaa58f12d861e8cdb6671c0f36880ceacc74ad7d6c4052a03"

      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.1/unbound-force_0.16.0-rc.1_linux_amd64.tar.gz"
      sha256 "19f2984c34ff3f074c2c68ff8bbd0f77cafbb701c3857049d83dc377858c3eed"
      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unbound-force/unbound-force/releases/download/v0.16.0-rc.1/unbound-force_0.16.0-rc.1_linux_arm64.tar.gz"
      sha256 "0a857662c78d714001967b6f415f7c0598a56b2f133b62b4a69a867c76eabf0a"
      define_method(:install) do
        bin.install "unbound-force"
        bin.install_symlink "unbound-force" => "uf"
      end
    end
  end
end
